### ISSUE TITLE
Feature Request: video captions and video labels

### ISSUE THREAD

**Issue by CBurton1** [MichaelJamesParsons/ustream-nodejs-sdk#15]
Any idea / timeline as to when these endpoints will be implemented for the video API?

**Comment by MichaelJamesParsons** [comment]
I added support for the following in #16:

- create label
- modify label
- delete label
- list labels
- add labels to video
- list labels assigned to video

The endpoint to remove labels from a video was giving me some grief. I'll look into it more tomorrow. Over the next couple days, I'll continue adding support for video labels and captions.

## Long term
To improve QOL and reduce maintenance overhead, I'm working on a revamp of this repository ([details](https://github.com/MichaelJamesParsons/ustream-nodejs-sdk/projects)). In order to dedicate more time toward that effort, feature development on `v1.x` will be reduced to a "by request" basis. If you need specific endpoints added beyond what you've already addressed here, please create an issue.

**Comment by MichaelJamesParsons** [comment]
I added support for all caption API endpoints in #17. Documentation will be updated in a separate PR, then these features will be formally released.

**Comment by MichaelJamesParsons** [comment]
Released in `1.5.0`
