### ISSUE TITLE
authRequest only supports query string params.

### ISSUE THREAD

**Issue by orangepek0e** [MichaelJamesParsons/ustream-nodejs-sdk#25]
Attempts to call modifyCaptionDetails appear to show that authRequest is taking the params that are intended to be sent through as data within the request body, and applying them as query string parameters.

ex:
`this.ustream.video.modifyCaptionDetails('<videoId>', 'en-US', {is_visible: true, is_default: true})`

After contacting the Watson Media team, it does appear that the issue is not on the Watson Media API, but is instead that they expect the `is_visible` and `is_default` as part of the Request body instead of appended as query params.

**Comment by MichaelJamesParsons** [comment]
I'm traveling right now. I'll get this resolved over the weekend.

**Comment by orangepek0e** [comment]
Do you have an ETA on when this issue may be resolved @MichaelJamesParsons ?

**Comment by MichaelJamesParsons** [comment]
I apologize for the delay. I was pulled away from this.

What you are experiencing does not appear to be a bug in `authRequest()`. The API endpoint expects request data with the content type  `application/x-www-form-urlencoded`, which is why you see a lot of `qs.stringify()` throughout the code base.

Your request is failing because `is_visible` and `is_default` expect a numeric value (0 or 1) to indicate whether they are set, not a boolean. The following will work as expected:

```
this.ustream.video.modifyCaptionDetails('<videoId>', 'en-US', {is_visible: 1, is_default: 1})
```

I'm not a fan of this design decision as it is very misleading. Regardless, some endpoints in Ustream's documentation include a sample request that may help debug issues such as this in the future. For example, the following can be found under the "modify caption details" section:

```
PUT videos/VIDEO_ID/captions/en-00.json HTTP/1.1
Host: api.video.ibm.com
Authorization: Bearer xxxxxxxxxxxxxx
Content-Type: application/x-www-form-urlencoded

is_visible=1&is_default=0
```

**Comment by orangepek0e** [comment]
@MichaelJamesParsons Sorry for the wait, your suggested change does seem to work in that the captions are now being uploaded successfully, however it does appear to still be throwing an error on success (which has caused a bit of confusion with regards to confirming whether the above change was successful or not)

however, the new error being returned is `TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them`. Just to put it on your radar as something to look into.

Thanks again for your reply!
